[package]
name = "kotori-renderer"
description = "Kotori IME: Windows 候補ウィンドウ(10.1、11.3)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
kotori-proto = { path = "../kotori-proto" }

[target.'cfg(windows)'.dependencies]
kotori-client = { path = "../kotori-client" }
