[package]
name = "kotori-server"
description = "Kotori IME: エンジン本体(4章)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = "1"
kotori-proto = { path = "../kotori-proto" }

[dev-dependencies]
kotori-client = { path = "../kotori-client" }

[target.'cfg(windows)'.dependencies]
kotori-client = { path = "../kotori-client" }

[target."cfg(unix)".dependencies]
fs4 = { version = "1.1.0", features = ["sync"] }
